version: "3.1"

services:
  backend:
    hostname: backend
    container_name: backend
    build:
      context: ..
      dockerfile: backend/Dockerfile
    networks:
      - bellis
    restart: always
    ports:
      - "7001:7001"
      - "2345:2345"

networks:
  bellis:
    external: true