version: "3.1"

services:
  backend:
    hostname: backend
    image: bellis-backend
    build:
      dockerfile: Dockerfile
      context: ..
      args:
        MODULE: backend
        PORT: 7001
    networks:
      - bellis
    restart: always
    ports:
      - "7001:7001"

  dispatcher:
    hostname: dispatcher
    image: bellis-dispatcher
    build:
      dockerfile: Dockerfile
      context: ..
      args:
        MODULE: dispatcher
    networks:
      - bellis
    restart: always

  envoy:
    hostname: envoy
    image: bellis-envoy
    build:
      dockerfile: Dockerfile
      context: ..
      args:
        MODULE: envoy
    networks:
      - bellis
    restart: always

  influxdb:
    hostname: influxdb
    image: influxdb
    networks:
      - bellis
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_ORG=bellis
      - DOCKER_INFLUXDB_INIT_BUCKET=backend
      - DOCKER_INFLUXDB_INIT_USERNAME=minoic
      - DOCKER_INFLUXDB_INIT_PASSWORD=Nightgod_
      - TZ=Asia/Shanghai
    ports:
      - "8086:8086"
    volumes:
      - /bellis/dist/database/influxdb:/var/lib/influxdb2
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.hostname==dev

  mongo1:
    hostname: mongo1
    image: mongo
    networks:
      - bellis
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - /bellis/dist/database/mongo1/configdb:/data/configdb
      - /bellis/dist/database/mongo1/db:/data/db
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.hostname==dev
  mongo2:
    hostname: mongo2
    image: mongo
    networks:
      - bellis
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - /bellis/dist/database/mongo2/configdb:/data/configdb
      - /bellis/dist/database/mongo2/db:/data/db
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.hostname==dev
  mongo3:
    hostname: mongo3
    image: mongo
    networks:
      - bellis
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - /bellis/dist/database/mongo3/configdb:/data/configdb
      - /bellis/dist/database/mongo3/db:/data/db'
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.hostname==dev

  mongo-init:
    image: mongo
    networks:
      - bellis
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    restart: on-failure
    command:
      - mongosh
      - mongodb://mongo1:27017/admin
      - --eval
      - 'rs.initiate({ _id: "rs0", members: [{_id:1,host:"mongo1:27017"},{_id:2,host:"mongo2:27017"},{_id:3,host:"mongo3:27017"}]})'

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    hostname: mongo-express
    ports:
      - "8081:8081"
    networks:
      - bellis
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    restart: always
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_URL=mongodb://mongo1,mongo2,mongo3?replicaSet=rs0
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.hostname==dev

  redis:
    hostname: redis
    image: redis
    networks:
      - bellis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /bellis/dist/database/redis:/data
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.hostname==dev

  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    networks:
      - bellis
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"
    depends_on:
      - redis
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.hostname==docker-desktop

  sentry:
    hostname: sentry
    image: bellis-sentry
    build:
      dockerfile: Dockerfile
      context: ..
      args:
        MODULE: sentry
    networks:
      - bellis
    restart: always


networks:
  bellis:
    driver: overlay
    external: true