version: "3.8"

services:
  # bellis containers
  backend:
    hostname: backend
    image: registry.cn-shanghai.aliyuncs.com/bellis/backend
    build:
      dockerfile: Dockerfile
      context: ..
      args:
        MODULE: backend
        PORT: 7001
    networks:
      - bellis
    ports:
      - "7001:7001"
    environment:
      - CONFIG_URL
  dispatcher:
    hostname: dispatcher
    image: registry.cn-shanghai.aliyuncs.com/bellis/dispatcher
    build:
      dockerfile: Dockerfile
      context: ..
      args:
        MODULE: dispatcher
    networks:
      - bellis
    environment:
      - CONFIG_URL
  envoy:
    hostname: envoy
    image: registry.cn-shanghai.aliyuncs.com/bellis/envoy
    build:
      dockerfile: Dockerfile
      context: ..
      args:
        MODULE: envoy
    environment:
      - CONFIG_URL
    networks:
      - bellis
  sentry:
    hostname: sentry
    image: registry.cn-shanghai.aliyuncs.com/bellis/sentry
    build:
      dockerfile: Dockerfile
      context: ..
      args:
        MODULE: sentry
    networks:
      - bellis
    environment:
      - CONFIG_URL

  # database containers
  influxdb:
    hostname: influxdb
    image: influxdb
    networks:
      - bellis
    environment:
      - DOCKER_INFLUXDB_INIT_ORG=bellis
      - DOCKER_INFLUXDB_INIT_BUCKET=backend
      - DOCKER_INFLUXDB_INIT_USERNAME=minoic
      - DOCKER_INFLUXDB_INIT_PASSWORD=Nightgod_
      - TZ=Asia/Shanghai
    ports:
      - "8086:8086"
    volumes:
      - ./dist/database/influxdb:/var/lib/influxdb2

networks:
  bellis:
    driver: overlay
    external: true