version: "3.8"

services:
  # bellis containers
  backend:
    image: registry.cn-shanghai.aliyuncs.com/bellis/backend
    build:
      dockerfile: modules/backend/Dockerfile
      context: ..
      args:
        MODULE: backend
  dispatcher:
    image: registry.cn-shanghai.aliyuncs.com/bellis/dispatcher
    build:
      dockerfile: Dockerfile
      context: ..
      args:
        MODULE: dispatcher
  envoy:
    image: registry.cn-shanghai.aliyuncs.com/bellis/envoy
    build:
      dockerfile: Dockerfile
      context: ..
      args:
        MODULE: envoy
  sentry:
    image: registry.cn-shanghai.aliyuncs.com/bellis/sentry
    build:
      dockerfile: Dockerfile
      context: ..
      args:
        MODULE: sentry/cmd/cluster
  sentry-singleton:
    image: registry.cn-shanghai.aliyuncs.com/bellis/sentry-singleton
    build:
      dockerfile: Dockerfile
      context: ..
      args:
        MODULE: sentry/cmd/singleton
