version: "3.1"

services:
  redis:
    hostname: redis
    container_name: redis
    image: redis
    networks:
      - bellis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./dist/database/redis:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    networks:
      - bellis
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"

networks:
  bellis:
    external: true