version: "3.1"

services:
  sentry:
    hostname: sentry
    container_name: sentry
    build:
      dockerfile: Dockerfile
      context: ..
      args:
        MODULE: sentry
    networks:
      - bellis
    restart: always

networks:
  bellis:
    external: true