name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: docker/login-action@v2
      name: Login to Docker registry
      with:
        registry: registry.cn-shanghai.aliyuncs.com
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build the Docker image
      run: DOCKER_BUILDKIT=1 docker-compose -f ./deploy/backend-build.yml build --progress=plain

    - name: Push the Docker image
      run: DOCKER_BUILDKIT=1 docker-compose -f ./deploy/backend-build.yml push --progress=plain
