name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker login registry.cn-shanghai.aliyuncs.com -u cytus_d -p ${{ secrets.REGISTRYPASSWORD }}
